## script used to update prep file names
## 
mv aglycon_04.prep  	aglycon_06.prep  
mv All_Dab_04.prep  	All_Dab_06.prep  
mv All_Lab_04.prep  	All_Lab_06.prep  
mv Alt_Dab_04.prep  	Alt_Dab_06.prep  
mv Alt_Lab_04.prep  	Alt_Lab_06.prep  
mv Ara_Dab_04.prep  	Ara_Dab_06.prep  
mv Ara_Ddu_04.prep  	Ara_Ddu_06.prep  
mv Ara_Lab_04.prep  	Ara_Lab_06.prep  
mv Ara_Ldu_04.prep  	Ara_Ldu_06.prep  
mv Fru_Dab_04.prep  	Fru_Dab_06.prep  
mv Fru_Ddu_04.prep  	Fru_Ddu_06.prep  
mv Fru_Lab_04.prep  	Fru_Lab_06.prep  
mv Fru_Ldu_04.prep  	Fru_Ldu_06.prep  
mv Fuc_Dab_04.prep  	Fuc_Dab_06.prep  
mv Fuc_Lab_04.prep  	Fuc_Lab_06.prep  
mv GalA_Dab_04.prep  	GalA_Dab_06.prep  
mv GalA_Lab_04.prep  	GalA_Lab_06.prep  
mv Gal_Dab_04.prep  	Gal_Dab_06.prep  
mv Gal_Lab_04.prep  	Gal_Lab_06.prep  
mv GalNAc_Dab_04.prep  	GalNAc_Dab_06.prep  
mv GalNAc_Lab_04.prep  	GalNAc_Lab_06.prep  
mv GlcA_Dab_04.prep  	GlcA_Dab_06.prep  
mv GlcA_Lab_04.prep  	GlcA_Lab_06.prep  
mv Glc_Dab_04.prep  	Glc_Dab_06.prep  
mv Glc_Lab_04.prep  	Glc_Lab_06.prep  
mv GlcNAc_Dab_04.prep  	GlcNAc_Dab_06.prep  
mv GlcNAc_Lab_04.prep  	GlcNAc_Lab_06.prep  
mv Gul_Dab_04.prep  	Gul_Dab_06.prep  
mv Gul_Lab_04.prep  	Gul_Lab_06.prep  
mv IdA_Lab_04.prep  	IdA_Lab_06.prep  
mv Lyx_Dab_04.prep  	Lyx_Dab_06.prep  
mv Lyx_Ddu_04.prep  	Lyx_Ddu_06.prep  
mv Lyx_Lab_04.prep  	Lyx_Lab_06.prep  
mv Lyx_Ldu_04.prep  	Lyx_Ldu_06.prep  
mv Man_Dab_04.prep  	Man_Dab_06.prep  
mv Man_Lab_04.prep  	Man_Lab_06.prep  
mv ManNAc_Dab_04.prep  	ManNAc_Dab_06.prep  
mv ManNAc_Lab_04.prep  	ManNAc_Lab_06.prep  
mv Neu5Ac_a_04.prep  	Neu5Ac_a_06.prep  
mv Psi_Dab_04.prep  	Psi_Dab_06.prep  
mv Psi_Ddu_04.prep  	Psi_Ddu_06.prep  
mv Psi_Lab_04.prep  	Psi_Lab_06.prep  
mv Psi_Ldu_04.prep  	Psi_Ldu_06.prep  
mv Qui_Dab_04.prep  	Qui_Dab_06.prep  
mv Qui_Lab_04.prep  	Qui_Lab_06.prep  
mv Rha_Dab_04.prep  	Rha_Dab_06.prep  
mv Rha_Lab_04.prep  	Rha_Lab_06.prep  
mv Rib_Dab_04.prep  	Rib_Dab_06.prep  
mv Rib_Ddu_04.prep  	Rib_Ddu_06.prep  
mv Rib_Lab_04.prep  	Rib_Lab_06.prep  
mv Rib_Ldu_04.prep  	Rib_Ldu_06.prep  
mv Sor_Dab_04.prep  	Sor_Dab_06.prep  
mv Sor_Ddu_04.prep  	Sor_Ddu_06.prep  
mv Sor_Lab_04.prep  	Sor_Lab_06.prep  
mv Sor_Ldu_04.prep  	Sor_Ldu_06.prep  
mv Tag_Dab_04.prep  	Tag_Dab_06.prep  
mv Tag_Ddu_04.prep  	Tag_Ddu_06.prep  
mv Tag_Lab_04.prep  	Tag_Lab_06.prep  
mv Tag_Ldu_04.prep  	Tag_Ldu_06.prep  
mv Tal_Dab_04.prep  	Tal_Dab_06.prep  
mv Tal_Lab_04.prep  	Tal_Lab_06.prep  
mv Tyv_Dab_04.prep  	Tyv_Dab_06.prep  
mv Tyv_Lab_04.prep  	Tyv_Lab_06.prep  
mv Xyl_Dab_04.prep  	Xyl_Dab_06.prep  
mv Xyl_Ddu_04.prep  	Xyl_Ddu_06.prep  
mv Xyl_Lab_04.prep  	Xyl_Lab_06.prep  
